<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>api_image_processor_aws</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="7.0.0" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.7.4" />
        <PackageReference Include="AWSSDK.SQS" Version="4.0.1.5" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
